name: Production deployment from master

on: 
  push:
    branches:
      - master

env:
  DBT_PROFILE_TARGET:            prod
  DBT_PROFILE_SCHEMA:            DBT_VIJAYRAJAGOPALAN
  DBT_PROFILE_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_PROFILE_SNOWFLAKE_ACCOUNT }}
  DBT_PROFILE_USER:              ${{ secrets.DBT_PROFILE_USER }}
  DBT_PROFILE_PASSWORD:          ${{ secrets.DBT_PROFILE_PASSWORD }}
  DBT_PROFILE_ROLE:              TRANSFORMER
  DBT_PROFILE_DB:                JAFFLE_SHOP
  DBT_PROFILE_WH:                COMPUTE_WH  

jobs:
  setup-envt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install DBT
      run: |
        mkdir -p ~/workspace/
        python -m venv ~/workspace/dbt-env
        source ~/workspace/dbt-env/bin/activate
        python -m pip install --upgrade pip
        pip install dbt

    - name: Cache-DBT-setup
      uses: actions/cache@v2
      env:
        cache-name: cache-dbt-setup
      with:
        # DBT runtime is stored in `~/bin` on Linux/macOS
        path: ~/workspace/dbt-env
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: DBT Compile
      run: |
        source ~/workspace/dbt-env/bin/activate
        dbt compile --profiles-dir ./ci_profiles

    - name: Archive manifest.json
      uses: actions/upload-artifact@v2
      with:
        name: manifest
        path: |
          ./target/manifest.json

  prod:
    environment: production
    runs-on: ubuntu-latest
    needs: setup-envt

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Cache-DBT-setup
      uses: actions/cache@v2
      env:
        cache-name: cache-dbt-setup
      with:
        # DBT runtime is stored in `~/bin` on Linux/macOS
        path: ~/workspace/dbt-env
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Download manifest.json
      uses: actions/download-artifact@v2
      with:
        name: manifest

    - name: Deploy
      run: |
        echo "LSLTR is $(ls -ltr)"
        source ~/workspace/dbt-env/bin/activate
        dbt run --profiles-dir ./ci_profiles
        dbt test --profiles-dir ./ci_profiles
    